Just some (minor) changes
Params and Build are singletons -- p and b (still waiting on naming rights!)
Commanders and Production should use simple_singletons module
All others use "use simple_params, only: p"  or "use simple_build, only:b" where appropriate
Strategy pointers to build and params removed

diff --git a/benchmarks/test_prime2D b/benchmarks/test_prime2D
--- a/benchmarks/test_prime2D
+++ b/benchmarks/test_prime2D
@@ -22,11 +22,18 @@ user	1m26.475s
 sys	0m1.997s"
 
 [ -d prime2D_bench ] && rm -rf prime2D_bench
-mkdir prime2D_bench && cd prime2D_bench
-
-nice simple_exec prg=import_particles ctf=yes smpd=1.275 cs=2.7 kv=300 fraca=0.1 deftab=../extract_params.txt stk=../sumstack.mrc projfile=betagal.simple
-time nice simple_distr_exec prg=cluster2D projfile=betagal.simple nparts=2 nthr=10 ncls=50 msk=88
-
+# mkdir prime2D_bench && cd prime2D_bench
+simple_exec prg=new_project projname=betagal_prime2D_bench
+if [ ! -d betagal_prime2D_bench ];then
+    echo ' simple_exec prg=new_project  FAILED!!!'
+    exit 1
+else
+    cd betagal_prime2D_bench
+    simple_exec prg=import_particles ctf=yes smpd=1.275 cs=2.7 deftab=../extract_params.txt fraca=0.1 kv=300 stk=../sumstack.mrc
+    #nice simple_exec prg=import_particles ctf=yes smpd=1.275 cs=2.7 kv=300 fraca=0.1 deftab=../extract_params.txt stk=../sumstack.mrc projfile=betagal.simple
+    #time nice simple_distr_exec prg=cluster2D projfile=betagal.simple nparts=2 nthr=10 ncls=50 msk=88
+    time simple_distr_exec prg=cluster2D ncls=100 msk=88 nparts=2 nthr=10
+fi
 #nohup simple_distr_exec prg=prime2D stk=../sumstack.mrc smpd=1.275 msk=88 ncls=100 ctf=yes nparts=4 nthr=8 deftab=../extract_params.txt > PRIME2D &
 # BGAL
 ## valgrind --tool=cachegrind simple_exec  prg=prime2D stk=../sumstack.mrc smpd=1.275 msk=88 ncls=100 ctf=yes nparts=4 nthr=8 deftab=../extract_params.txt
