benchmarks updated with new_project/import methods

diff --git a/benchmarks/test_prime3D b/benchmarks/test_prime3D
--- a/benchmarks/test_prime3D
+++ b/benchmarks/test_prime3D
@@ -12,12 +12,26 @@ if [ ! -d "${SIMPLE_TESTBENCH_DATA}/bgal" ]; then
 fi
 
 cd ${SIMPLE_TESTBENCH_DATA}/bgal
-prime_cleanup.pl
-pkill simple_exec
-[ -d prime3D_bench ] && rm -rf prime3D_bench
-mkdir prime3D_bench && cd prime3D_bench
-simple_private_exec prg=import_cavgs   stk=../cavgs_final_ranked.mrc smpd=2.55 projfile=prime3Dtest.simple projname=prime3Dtest
-#simple_private_exec prg=import_particles ctf=yes pgrp=d2 deftab=../extract_params.txtoritab=../prime3Ddoc_035.txt  stk=../scaledsel.mrc smpd=2.55 projfile=prime3Dtest.simple nparts=2 mul=0.5 msk=40
-nohup simple_distr_exec prg=refine3D stk=../scaledsel.mrc oritab=../prime3Ddoc_035.txt ctf=yes smpd=2.55 msk=40 pgrp=d2 deftab=../extract_params.txt eo=yes nparts=2 nthr=8 mul=0.5 > PRIME3D &
-
+#prime_cleanup.pl
+#pkill simple_exec
+ [ -d prime3D_bench ] && rm -rf prime3D_bench
+# simple_exec prg=new_project projname=prime3D_bench
+# if [ -d prime3D_bench ]; then
+#     cd prime3D_bench
+# simple_exec prg=import_cavgs   stk=../cavgs_final_ranked.mrc smpd=2.55 projfile=prime3D_bench.simple projname=prime3D_bench
+# #simple_private_exec prg=import_particles ctf=yes pgrp=d2 deftab=../extract_params.txt oritab=../prime3Ddoc_035.txt  stk=../scaledsel.mrc smpd=2.55 projfile=prime3Dtest.simple nparts=2 mul=0.5 msk=40
+# time  simple_distr_exec prg=refine3D stk=../scaledsel.mrc oritab=../prime3Ddoc_035.txt ctf=yes smpd=2.55 msk=40 pgrp=d2 deftab=../extract_params.txt eo=yes nparts=2 nthr=8 mul=0.5 > PRIME3D &
+# fi
 # simple_distr_exec prg=prime3D stk=scaledstack.mrc ctf=yes smpd=2.55 msk=40 pgrp=d2 deftab=../extract_params.txt eo=yes nparts=2 nthr=8 vol1=startvol_state01.mrc lp=15 PRIME3D
+simple_exec prg=new_project projname=prime3D_bench
+
+
+if [ ! -d prime3D_bench ];then
+    echo ' simple_exec prg=new_project  FAILED!!!'
+    exit 1
+else
+    cd prime3D_bench
+    simple_exec prg=import_particles ctf=yes smpd=1.275 cs=2.7 deftab=../extract_params.txt fraca=0.1 kv=300 stk=../scaledsel.mrc oritab=../prime3Ddoc_035.txt ctf=yes smpd=2.55 msk=40 projfile=prime3D_bench.simple projname=prime3D_bench
+
+    time simple_distr_exec prg=cluster3D ncls=100 msk=40 nparts=2 nthr=10 projfile=prime3D_bench.simple projname=prime3D_bench
+fi
